# https://developers.home-assistant.io/docs/add-ons/configuration#add-on-dockerfile
labels:
  org.opencontainers.image.title: "PufferPanel"
  org.opencontainers.image.description: "Panel for hosting different containerized gameservers"
  org.opencontainers.image.source: "https://github.com/matebuteler/pufferpanel-hass"
  org.opencontainers.image.licenses: "MIT"
